name: "Daily Fetch"
on:
  workflow_dispatch:
  schedule:
    - cron:  '12 5 * * *'
permissions:
  contents: write
jobs:
  fetchData:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: v20.16.x
          cache: npm
      - name: Install
        run: npm install
      - name: Run My Script
        run: |
          npm run pullData
      - name: Commit updated data
        continue-on-error: true
        run: |
          git config --global user.name 'Casey Botts'
          git config --global user.email 'casey.s.watts+bot@gmail.com'
          git add src/data
          git commit -m "update data"
          git push